version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: device_db
      POSTGRES_USER: device_user
      POSTGRES_PASSWORD: device_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/device_db
      SPRING_DATASOURCE_USERNAME: device_user
      SPRING_DATASOURCE_PASSWORD: device_password
    ports:
      - "8080:8080"

volumes:
  postgres-data: